### PR TITLE
Removed show likes link to users that can't see likes

### PR DESCRIPTION
**Pull request by chack1172**
Should we remove the link also in profile page and in postbit when no permission?

### CODE REVIEW

**Comment by euantorano** [comment]
Yes, I'd say we should do it in both profile and postbit too.

We should also move the HTML into a template, rather than having it in the code.

**Comment by chack1172** [comment]
Instead of template, we can use a better language variable with link inside it. Instead of removing links, why don't we just show an error? We can leave link in profile page and post, when they click it there's already an error no permission page. We should only handle errors when opening modal.

**Comment by chack1172** [comment]
Doing this we can also have a better language variable with link inside it.

**Comment by euantorano** [comment]
Looks good to me, I just need to find time to give it a test.

**Comment by chack1172** [comment]
Ok, I already checked it but it's better if we do more tests. I'm going to push a commit to fix no permission modal.

**Pull request merged**
